name: Build OS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install qemu && make
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential qemu-system-i386 make

      - name: Build
        run: make

      - name: Check if kernel exists
        id: check_kernel
        uses: andstor/file-existence-action@v2
        with:
          files: kernel.elf

      - name: Run tests
        if: steps.check_kernel.outputs.files_exists == 'true'
        run: qemu-system-i386 -kernel kernel.elf -nographic -serial mon:stdio

      - name: Upload kernel (optional)
        if: steps.check_kernel.outputs.files_exists == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: kernel
          path: kernel.elf
